using System;
using System.Collections.Generic;
using System.Linq;
using EHub.Permissions;
using EHub.ShopManagement.Units;
using Volo.Abp.DependencyInjection;

namespace EHub.ShopManagement.AiAssistant;

/// <summary>
/// Hand-authored registry, one entry per Shop Management module, built directly from the real
/// Create*Dto classes (ShopUnitEditDtoBase, CreateUpdateShopCustomerDto, etc.) - see the comment on
/// each module for which file it mirrors. This is the ONLY place field names/types/requiredness
/// come from; nothing here is generated by or accepted from Ollama.
///
/// Fields deliberately NOT registered anywhere in this file (per the "must not include" list):
/// TenantId, audit fields (CreationTime/CreatorId/etc.), generated document numbers (Code is
/// listed as IsSystemGenerated for AI purposes even where the human UI lets a user type it - the
/// AI never invents one either), calculated balances, CurrentStock, posting user/date fields, and
/// backend-owned Status fields.
/// </summary>
public class ShopAiModuleMetadataProvider : IShopAiModuleMetadataProvider, ISingletonDependency
{
    private readonly List<ShopAiModuleMetadata> _modules;
    private readonly Dictionary<string, ShopAiModuleMetadata> _byKey;
    private readonly Dictionary<string, ShopAiModuleMetadata> _byAlias;

    public ShopAiModuleMetadataProvider()
    {
        _modules = BuildModules();
        _byKey = _modules.ToDictionary(m => m.ModuleKey, StringComparer.OrdinalIgnoreCase);
        _byAlias = new Dictionary<string, ShopAiModuleMetadata>(StringComparer.OrdinalIgnoreCase);
        foreach (var module in _modules)
        {
            _byAlias[module.ModuleKey] = module;
            _byAlias[module.DisplayName] = module;
            foreach (var alias in module.Aliases)
            {
                _byAlias.TryAdd(alias, module);
            }
        }
    }

    public ShopAiModuleMetadata GetModule(string moduleKey) =>
        _byKey.TryGetValue(moduleKey, out var m) ? m : throw new KeyNotFoundException($"Unknown ShopAi module key '{moduleKey}'.");

    public IReadOnlyList<ShopAiModuleMetadata> GetModules() => _modules;

    public bool TryGetModule(string moduleNameOrAlias, out ShopAiModuleMetadata? metadata)
    {
        if (string.IsNullOrWhiteSpace(moduleNameOrAlias))
        {
            metadata = null;
            return false;
        }

        return _byAlias.TryGetValue(moduleNameOrAlias.Trim(), out metadata);
    }

    public bool TryFindModuleInText(string text, out ShopAiModuleMetadata? metadata)
    {
        metadata = null;
        if (string.IsNullOrWhiteSpace(text)) return false;

        ShopAiModuleMetadata? best = null;
        var bestLength = 0;
        foreach (var module in _modules)
        {
            foreach (var candidate in new[] { module.ModuleKey, module.DisplayName }.Concat(module.Aliases))
            {
                // Skip very short tokens (e.g. "po") - they match too much unrelated text to be a
                // reliable signal on their own.
                if (string.IsNullOrWhiteSpace(candidate) || candidate.Length < 3) continue;
                if (candidate.Length > bestLength && text.Contains(candidate, StringComparison.OrdinalIgnoreCase))
                {
                    best = module;
                    bestLength = candidate.Length;
                }
            }
        }

        metadata = best;
        return best != null;
    }

    // ------------------------------------------------------------------
    // Field helpers
    // ------------------------------------------------------------------

    private static ShopAiFieldMetadata Field(
        string key, string display, string description, string dataType, bool required,
        string? example = null, bool isLookup = false, string? lookupModule = null,
        bool isSystemGenerated = false, bool isCalculated = false, decimal? min = null, decimal? max = null,
        int? maxLength = null, List<string>? allowedValues = null, List<string>? aliases = null,
        string? descriptionUrdu = null, string? descriptionRomanUrdu = null,
        string? askPromptEnglish = null, string? askPromptUrdu = null, string? askPromptRomanUrdu = null) => new()
    {
        FieldKey = key,
        DisplayName = display,
        Description = description,
        DescriptionUrdu = descriptionUrdu,
        DescriptionRomanUrdu = descriptionRomanUrdu,
        AskPromptEnglish = askPromptEnglish,
        AskPromptUrdu = askPromptUrdu,
        AskPromptRomanUrdu = askPromptRomanUrdu,
        DataType = dataType,
        IsRequired = required,
        IsLookup = isLookup,
        LookupModuleKey = lookupModule,
        IsSystemGenerated = isSystemGenerated,
        IsCalculated = isCalculated,
        IsUserEditable = !isSystemGenerated && !isCalculated,
        ExampleValue = example,
        MinimumValue = min,
        MaximumValue = max,
        MaximumLength = maxLength,
        AllowedValues = allowedValues ?? new List<string>(),
        Aliases = aliases ?? new List<string>(),
    };

    // ------------------------------------------------------------------
    // Registry
    // ------------------------------------------------------------------

    private static List<ShopAiModuleMetadata> BuildModules()
    {
        var modules = new List<ShopAiModuleMetadata>();

        // ---------------- Master data (guided creation approved) ----------------

        // Mirrors CreateUpdateShopProductCategoryDto.
        modules.Add(new ShopAiModuleMetadata
        {
            ModuleKey = "productcategory",
            DisplayName = "Product Category",
            Description = "A Product Category groups related products together (e.g. Plumbing, Electrical) for organization, filtering, and reporting. Categories can be nested under a parent category.",
            CreateAction = ShopAiActionType.CreateProductCategory,
            RequiredPermission = EHubPermissions.ShopAiAssistant.CreateProductCategory,
            ExistingCreatePermission = EHubPermissions.ShopProductCategories.Create,
            SupportsCreation = true,
            CreatesDraftOnly = false,
            Aliases = new() { "category", "categories", "product category", "categorization", "کیٹیگری", "category add", "category banana" },
            Fields = new()
            {
                Field("name", "Name", "The category's display name.", "String", true, "Plumbing", maxLength: 200),
                Field("code", "Code", "A short unique code identifying the category.", "String", true, "PLM", maxLength: 32),
                Field("parentCategoryId", "Parent Category", "An existing category this one nests under, if any.", "String", false, "Plumbing Accessories", isLookup: true, lookupModule: "productcategory"),
                Field("description", "Description", "Free-text notes about the category.", "String", false, maxLength: 1000),
                Field("displayOrder", "Display Order", "Sort position among sibling categories.", "Integer", false, "1", min: 0),
                Field("isActive", "Active", "Whether the category is selectable for new products. Defaults to yes.", "Boolean", false, "Yes"),
            },
            BusinessRules = new()
            {
                "Category code must be unique within the shop.",
                "A category can optionally have a parent category to build a hierarchy.",
            },
            RelatedModules = new() { "product" },
        });

        // Mirrors CreateUpdateShopUnitDto exactly - no Description field exists on this DTO. Max
        // lengths (64/16) come from ShopUnitConsts, the same constants ShopUnitManager validates
        // against - kept in sync deliberately rather than duplicated as magic numbers.
        modules.Add(new ShopAiModuleMetadata
        {
            ModuleKey = "unit",
            DisplayName = "Unit",
            Description = "A Unit defines how a product quantity is measured, such as Piece, Meter, Kilogram, Liter, Box, or Pack.",
            DescriptionUrdu = "یونٹ اس بات کی وضاحت کرتا ہے کہ کسی پروڈکٹ کی مقدار کس پیمانے میں ریکارڈ کی جائے گی، جیسے عدد، میٹر، کلوگرام، لیٹر، ڈبہ یا پیک۔",
            DescriptionRomanUrdu = "Unit yeh define karti hai ke product ki quantity kis measurement mein record hogi, jaise Piece, Meter, Kilogram, Liter, Box ya Pack.",
            CreateAction = ShopAiActionType.CreateUnit,
            RequiredPermission = EHubPermissions.ShopAiAssistant.CreateUnit,
            ExistingCreatePermission = EHubPermissions.ShopUnits.Create,
            SupportsCreation = true,
            CreatesDraftOnly = false,
            Aliases = new() { "unit", "units", "measurement unit", "shop unit", "اکائی", "پیمائش", "unit add", "unit banana" },
            Fields = new()
            {
                Field("name", "Name", "The unit's full name.", "String", true, "Piece", maxLength: ShopUnitConsts.NameMaxLength,
                    descriptionUrdu: "یونٹ کا مکمل نام، جیسے عدد، کلوگرام یا میٹر۔",
                    descriptionRomanUrdu: "Unit ka complete naam, jaise Piece, Kilogram ya Meter.",
                    askPromptEnglish: "What should the Unit's Name be? (e.g. Piece)",
                    askPromptUrdu: "یونٹ کا نام بتائیں۔",
                    askPromptRomanUrdu: "Unit Name bata dein."),
                Field("shortName", "Short Name", "A short abbreviation shown throughout the app.", "String", true, "Pc", maxLength: ShopUnitConsts.ShortNameMaxLength,
                    descriptionUrdu: "انوائس اور فہرستوں میں دکھایا جانے والا مختصر نام۔",
                    descriptionRomanUrdu: "Invoice aur grids mein show hone wala short naam.",
                    askPromptEnglish: "What should the Short Name be? (e.g. Pc)",
                    askPromptUrdu: "مختصر نام بتائیں۔",
                    askPromptRomanUrdu: "Short Name bata dein."),
                Field("allowDecimal", "Allow Decimal Quantity", "Whether products in this unit can be sold/stocked in fractional amounts (e.g. 1.5).", "Boolean", true, "No",
                    descriptionUrdu: "اگر ہاں ہو تو 1.5، 2.25 جیسی مقدار قابلِ قبول ہوگی۔ اگر نہیں ہو تو صرف 1، 2، 3 جیسی مکمل مقدار قابلِ قبول ہوگی۔",
                    descriptionRomanUrdu: "Agar Yes ho to 1.5, 2.25 jaisi quantity allowed hogi. Agar No ho to sirf 1, 2, 3 jaisi whole quantity allowed hogi. Misalen: Piece -> No, Box -> No, Kilogram -> Yes, Meter -> Yes, Liter -> Yes.",
                    askPromptEnglish: "Should decimal quantity be allowed? (Yes/No)",
                    askPromptUrdu: "کیا اعشاریہ مقدار کی اجازت ہو؟ (ہاں/نہیں)",
                    askPromptRomanUrdu: "Kya decimal quantity allow karni hai? (Yes/No)"),
                Field("isActive", "Active", "Whether the unit is selectable for new products. Defaults to yes.", "Boolean", false, "Yes",
                    descriptionUrdu: "فعال یونٹ نئے پراڈکٹس میں منتخب کی جا سکتی ہے۔ غیر فعال یونٹ نئے پراڈکٹس میں منتخب نہیں ہونی چاہیے۔",
                    descriptionRomanUrdu: "Active Unit products mein select ki ja sakti hai. Inactive Unit new products mein select nahi honi chahiye.",
                    askPromptEnglish: "Should the Unit be Active? (Yes/No) Default: Yes",
                    askPromptUrdu: "کیا یونٹ فعال رکھنی ہے؟ (ہاں/نہیں) ڈیفالٹ: ہاں",
                    askPromptRomanUrdu: "Kya Unit Active rakhni hai? (Yes/No) Default: Yes"),
            },
            BusinessRules = new()
            {
                "Unit name must be unique within the shop.",
                "Whole-count units such as Piece normally use Allow Decimal = No.",
                "Weight, length, and volume units (Kilogram, Meter, Liter) normally use Allow Decimal = Yes.",
            },
            RelatedModules = new() { "product" },
        });

        // Mirrors ShopProductEditDtoBase (CreateShopProductDto). CurrentStock is deliberately
        // absent - it is never a creation input, only ever changed via stock transactions.
        modules.Add(new ShopAiModuleMetadata
        {
            ModuleKey = "product",
            DisplayName = "Product",
            Description = "A Product is an item the shop buys and sells. It belongs to a Category, is measured in a Unit, and carries pricing, tax, and stock-control settings.",
            CreateAction = ShopAiActionType.CreateProduct,
            RequiredPermission = EHubPermissions.ShopAiAssistant.CreateProduct,
            ExistingCreatePermission = EHubPermissions.ShopProducts.Create,
            SupportsCreation = true,
            CreatesDraftOnly = false,
            Aliases = new() { "product", "products", "item", "پروڈکٹ", "product add", "product banana" },
            Fields = new()
            {
                Field("categoryId", "Category", "The product category it belongs to.", "String", true, "Plumbing", isLookup: true, lookupModule: "productcategory"),
                Field("unitId", "Unit", "How the product's quantity is measured.", "String", true, "Piece", isLookup: true, lookupModule: "unit"),
                Field("name", "Name", "The product's display name.", "String", true, "PVC Pipe 1 Inch", maxLength: 200),
                Field("code", "Code", "A unique internal code for the product.", "String", true, "PVC-1IN", maxLength: 64),
                Field("sku", "SKU", "Optional stock-keeping unit code.", "String", false, maxLength: 64),
                Field("barcode", "Barcode", "Optional scannable barcode value.", "String", false, maxLength: 64),
                Field("description", "Description", "Free-text product notes.", "String", false, maxLength: 1000),
                Field("brand", "Brand", "Optional brand/manufacturer name.", "String", false, maxLength: 100),
                Field("model", "Model", "Optional model number/name.", "String", false, maxLength: 100),
                Field("purchasePrice", "Purchase Price", "Cost price the shop pays per unit.", "Decimal", true, "250", min: 0),
                Field("salePrice", "Sale Price", "Price the shop sells at per unit.", "Decimal", true, "300", min: 0),
                Field("wholesalePrice", "Wholesale Price", "Optional bulk/wholesale price.", "Decimal", false, min: 0),
                Field("minimumSalePrice", "Minimum Sale Price", "Optional floor below which the sale price cannot go.", "Decimal", false, min: 0),
                Field("taxPercentage", "Tax Percentage", "Tax rate applied to sales of this product.", "Decimal", false, "0", min: 0, max: 100),
                Field("minimumStockLevel", "Minimum Stock Level", "Stock level considered the safety minimum.", "Decimal", false, "0", min: 0),
                Field("maximumStockLevel", "Maximum Stock Level", "Optional upper stock target.", "Decimal", false, min: 0),
                Field("reorderLevel", "Reorder Level", "Stock level at which the product is flagged for reordering.", "Decimal", false, "0", min: 0),
                Field("trackBatch", "Track Batch", "Whether stock is tracked by batch number.", "Boolean", false, "No"),
                Field("trackExpiry", "Track Expiry", "Whether stock is tracked by expiry date.", "Boolean", false, "No"),
                Field("expiryAlertDays", "Expiry Alert Days", "Days before expiry to start warning. Only relevant when Track Expiry is on.", "Integer", false, min: 0),
                Field("trackSerialNumber", "Track Serial Number", "Whether individual units are tracked by serial number.", "Boolean", false, "No"),
                Field("isTaxable", "Taxable", "Whether tax applies to this product at all.", "Boolean", false, "No"),
                Field("isActive", "Active", "Whether the product is available for sale. Defaults to yes.", "Boolean", false, "Yes"),
            },
            BusinessRules = new()
            {
                "Product code must be unique within the shop.",
                "Prices, stock levels, and tax percentage cannot be negative.",
                "CurrentStock is never set directly - it only changes via Goods Receipts, Sales, Stock Adjustments, and Stock Counts.",
            },
            RelatedModules = new() { "productcategory", "unit", "stocktransactions", "productbatches" },
        });

        // Mirrors CreateUpdateShopCustomerDto. Code is system-generated when created via AI.
        modules.Add(new ShopAiModuleMetadata
        {
            ModuleKey = "customer",
            DisplayName = "Customer",
            Description = "A Customer is a person or business the shop sells products to. Customers can have a credit limit, payment terms, and an opening balance for ledger tracking.",
            CreateAction = ShopAiActionType.CreateCustomer,
            RequiredPermission = EHubPermissions.ShopAiAssistant.CreateCustomer,
            ExistingCreatePermission = EHubPermissions.ShopCustomers.Create,
            SupportsCreation = true,
            CreatesDraftOnly = false,
            Aliases = new() { "customer", "customers", "client", "کسٹمر", "customer add", "customer banana" },
            Fields = new()
            {
                Field("code", "Code", "A unique customer code.", "String", false, isSystemGenerated: true),
                Field("name", "Name", "The customer's full name or business name.", "String", true, "Ali Traders", maxLength: 200),
                Field("contactPerson", "Contact Person", "Optional contact person name.", "String", false, maxLength: 128),
                Field("phone", "Phone", "Optional phone number.", "String", false, "03001234567", maxLength: 32),
                Field("alternatePhone", "Alternate Phone", "Optional second phone number.", "String", false, maxLength: 32),
                Field("email", "Email", "Optional email address.", "String", false, maxLength: 256),
                Field("addressLine1", "Address Line 1", "Optional street address.", "String", false, maxLength: 256),
                Field("addressLine2", "Address Line 2", "Optional additional address line.", "String", false, maxLength: 256),
                Field("city", "City", "Optional city.", "String", false, maxLength: 100),
                Field("stateOrProvince", "State/Province", "Optional state or province.", "String", false, maxLength: 100),
                Field("postalCode", "Postal Code", "Optional postal code.", "String", false, maxLength: 32),
                Field("country", "Country", "Optional country.", "String", false, maxLength: 100),
                Field("taxNumber", "Tax Number", "Optional tax registration number.", "String", false, maxLength: 64),
                Field("openingBalance", "Opening Balance", "Starting receivable balance for the customer ledger.", "Decimal", false, "0", min: 0),
                Field("creditLimit", "Credit Limit", "Maximum credit the customer is allowed.", "Decimal", false, "0", min: 0),
                Field("paymentTermsDays", "Payment Terms (Days)", "Days allowed to pay after a credit sale.", "Integer", false, "0", min: 0),
                Field("notes", "Notes", "Free-text notes.", "String", false, maxLength: 1000),
                Field("isActive", "Active", "Whether the customer can be selected on new sales. Defaults to yes.", "Boolean", false, "Yes"),
            },
            BusinessRules = new()
            {
                "Customer code is generated by the system when created via the AI Assistant, never typed by the user.",
                "Opening balance and credit limit cannot be negative.",
                "Only one Walk-in customer is allowed per shop - the AI does not create walk-in customers.",
            },
            RelatedModules = new() { "sales", "customerpayments", "customerledger", "salereturns" },
        });

        // Mirrors CreateUpdateShopSupplierDto. Same Code-is-system-generated rule as Customer.
        modules.Add(new ShopAiModuleMetadata
        {
            ModuleKey = "supplier",
            DisplayName = "Supplier",
            Description = "A Supplier is a vendor the shop buys products from. Suppliers can have a credit limit, payment terms, and an opening balance for ledger tracking.",
            CreateAction = ShopAiActionType.CreateSupplier,
            RequiredPermission = EHubPermissions.ShopAiAssistant.CreateSupplier,
            ExistingCreatePermission = EHubPermissions.ShopSuppliers.Create,
            SupportsCreation = true,
            CreatesDraftOnly = false,
            Aliases = new() { "supplier", "suppliers", "vendor", "سپلائر", "supplier add", "supplier banana" },
            Fields = new()
            {
                Field("code", "Code", "A unique supplier code.", "String", false, isSystemGenerated: true),
                Field("name", "Name", "The supplier's business name.", "String", true, "ABC Traders", maxLength: 200),
                Field("contactPerson", "Contact Person", "Optional contact person name.", "String", false, maxLength: 128),
                Field("phone", "Phone", "Optional phone number.", "String", false, maxLength: 32),
                Field("alternatePhone", "Alternate Phone", "Optional second phone number.", "String", false, maxLength: 32),
                Field("email", "Email", "Optional email address.", "String", false, maxLength: 256),
                Field("addressLine1", "Address Line 1", "Optional street address.", "String", false, maxLength: 256),
                Field("addressLine2", "Address Line 2", "Optional additional address line.", "String", false, maxLength: 256),
                Field("city", "City", "Optional city.", "String", false, maxLength: 100),
                Field("stateOrProvince", "State/Province", "Optional state or province.", "String", false, maxLength: 100),
                Field("postalCode", "Postal Code", "Optional postal code.", "String", false, maxLength: 32),
                Field("country", "Country", "Optional country.", "String", false, maxLength: 100),
                Field("taxNumber", "Tax Number", "Optional tax registration number.", "String", false, maxLength: 64),
                Field("openingBalance", "Opening Balance", "Starting payable balance for the supplier ledger.", "Decimal", false, "0", min: 0),
                Field("creditLimit", "Credit Limit", "Maximum credit the supplier extends.", "Decimal", false, "0", min: 0),
                Field("paymentTermsDays", "Payment Terms (Days)", "Days allowed to pay after a purchase.", "Integer", false, "0", min: 0),
                Field("notes", "Notes", "Free-text notes.", "String", false, maxLength: 1000),
                Field("isActive", "Active", "Whether the supplier can be selected on new purchases. Defaults to yes.", "Boolean", false, "Yes"),
            },
            BusinessRules = new()
            {
                "Supplier code is generated by the system when created via the AI Assistant, never typed by the user.",
                "Opening balance and credit limit cannot be negative.",
            },
            RelatedModules = new() { "purchaseorders", "supplierpayments", "supplierledger", "purchasereturns" },
        });

        // Mirrors CreateUpdateShopExpenseCategoryDto.
        modules.Add(new ShopAiModuleMetadata
        {
            ModuleKey = "expensecategory",
            DisplayName = "Expense Category",
            Description = "An Expense Category groups similar expenses together, such as Electricity, Rent, or Salaries, for reporting.",
            CreateAction = ShopAiActionType.CreateExpenseCategory,
            RequiredPermission = EHubPermissions.ShopAiAssistant.CreateExpenseCategory,
            ExistingCreatePermission = EHubPermissions.ShopExpenseCategories.Create,
            SupportsCreation = true,
            CreatesDraftOnly = false,
            Aliases = new() { "expense category", "expense categories", "اخراجات کیٹیگری", "expense category add" },
            Fields = new()
            {
                Field("code", "Code", "A unique short code for the category.", "String", true, "ELEC", maxLength: 32),
                Field("name", "Name", "The category's display name.", "String", true, "Electricity", maxLength: 200),
                Field("description", "Description", "Optional notes about the category.", "String", false, maxLength: 1000),
                Field("isActive", "Active", "Whether the category is selectable for new expenses. Defaults to yes.", "Boolean", false, "Yes"),
            },
            BusinessRules = new() { "Expense category code must be unique within the shop." },
            RelatedModules = new() { "expenses" },
        });

        // Mirrors CreateUpdateShopBankAccountDto.
        modules.Add(new ShopAiModuleMetadata
        {
            ModuleKey = "bankaccount",
            DisplayName = "Bank Account",
            Description = "A Bank Account represents one of the shop's bank accounts, used as a payment source/destination for expenses, supplier payments, customer payments, and bank transfers.",
            CreateAction = ShopAiActionType.CreateBankAccount,
            RequiredPermission = EHubPermissions.ShopAiAssistant.CreateBankAccount,
            ExistingCreatePermission = EHubPermissions.ShopBankAccounts.Create,
            SupportsCreation = true,
            CreatesDraftOnly = false,
            Aliases = new() { "bank account", "bank accounts", "bank", "بینک اکاؤنٹ", "bank account add" },
            Fields = new()
            {
                Field("code", "Code", "A unique short code for the account.", "String", true, "HBL-001", maxLength: 32),
                Field("accountName", "Account Name", "The account holder / display name.", "String", true, "Main Business Account", maxLength: 200),
                Field("bankName", "Bank Name", "The bank this account is held at.", "String", true, "HBL", maxLength: 200),
                Field("accountNumber", "Account Number", "Optional account number.", "String", false, maxLength: 64),
                Field("iban", "IBAN", "Optional IBAN.", "String", false, maxLength: 64),
                Field("branchName", "Branch Name", "Optional branch name.", "String", false, maxLength: 128),
                Field("openingBalance", "Opening Balance", "Starting balance for this account. Cannot be negative.", "Decimal", false, "0", min: 0),
                Field("isDefault", "Default Account", "Whether this becomes the default bank account for new transactions.", "Boolean", false, "No"),
                Field("isActive", "Active", "Whether the account can be used for new transactions. Defaults to yes.", "Boolean", false, "Yes"),
                Field("notes", "Notes", "Optional free-text notes.", "String", false, maxLength: 1000),
            },
            BusinessRules = new() { "Account code must be unique within the shop.", "Opening balance cannot be negative." },
            RelatedModules = new() { "banktransactions", "banktransfers", "expenses", "supplierpayments", "customerpayments" },
        });

        // ---------------- Draft transactions (guided creation approved, draft only) ----------------

        // Mirrors CreateUpdateShopExpenseDto.
        modules.Add(new ShopAiModuleMetadata
        {
            ModuleKey = "expensedraft",
            DisplayName = "Expense",
            Description = "An Expense records money the shop spent, such as electricity or rent. Created by the AI Assistant as a Draft only - it does not reduce cash or bank balance until posted through the normal Expenses screen.",
            CreateAction = ShopAiActionType.CreateExpenseDraft,
            RequiredPermission = EHubPermissions.ShopAiAssistant.CreateExpenseDraft,
            ExistingCreatePermission = EHubPermissions.ShopExpenses.Create,
            SupportsCreation = true,
            CreatesDraftOnly = true,
            Aliases = new() { "expense", "expenses", "spending", "اخراجات", "expense add" },
            Fields = new()
            {
                Field("expenseCategoryId", "Expense Category", "Which category this expense belongs to.", "String", true, "Electricity", isLookup: true, lookupModule: "expensecategory"),
                Field("expenseDate", "Expense Date", "The date the expense occurred.", "DateTime", true, "29-Jul-2026"),
                Field("amount", "Amount", "The expense amount. Must be greater than zero.", "Decimal", true, "5000", min: 0.01m),
                Field("paymentMethod", "Payment Method", "How the expense was/will be paid.", "Enum", true, allowedValues: new() { "Cash", "Bank", "Card", "Cheque", "Other" }),
                Field("paidTo", "Paid To", "Optional payee name.", "String", false, maxLength: 200),
                Field("referenceNumber", "Reference Number", "Optional reference number.", "String", false, maxLength: 128),
                Field("chequeNumber", "Cheque Number", "Required when Payment Method is Cheque.", "String", false, maxLength: 64),
                Field("bankName", "Bank Name", "Required when Payment Method is Cheque or Bank.", "String", false, maxLength: 128),
                Field("bankAccountId", "Bank Account", "Required when Payment Method is Bank.", "String", false, isLookup: true, lookupModule: "bankaccount"),
                Field("description", "Description", "What the expense was for.", "String", false, maxLength: 500),
                Field("notes", "Notes", "Optional additional notes.", "String", false, maxLength: 1000),
            },
            BusinessRules = new()
            {
                "Amount must be greater than zero.",
                "The AI creates the expense as Draft only - it never posts it, so cash/bank balance is unaffected until someone posts it from the Expenses screen.",
            },
            RelatedModules = new() { "expensecategory", "bankaccount", "cashregisters" },
        });

        // Mirrors CreateShopPurchaseOrderDto + CreateShopPurchaseOrderItemDto.
        modules.Add(new ShopAiModuleMetadata
        {
            ModuleKey = "purchaseorderdraft",
            DisplayName = "Purchase Order",
            Description = "A Purchase Order records an order placed with a Supplier for one or more Products. Created by the AI Assistant as a Draft only - it does not affect stock or the supplier ledger until approved and received through the normal flow.",
            CreateAction = ShopAiActionType.CreatePurchaseOrderDraft,
            RequiredPermission = EHubPermissions.ShopAiAssistant.CreatePurchaseOrderDraft,
            ExistingCreatePermission = EHubPermissions.ShopPurchaseOrders.Create,
            SupportsCreation = true,
            CreatesDraftOnly = true,
            Aliases = new() { "purchase order", "purchase orders", "po", "خریداری آرڈر", "purchase order add" },
            Fields = new()
            {
                Field("supplierId", "Supplier", "Which supplier the order is placed with.", "String", true, "ABC Traders", isLookup: true, lookupModule: "supplier"),
                Field("orderDate", "Order Date", "The date the order is placed.", "DateTime", true),
                Field("expectedDeliveryDate", "Expected Delivery Date", "Optional expected delivery date.", "DateTime", false),
                Field("supplierReference", "Supplier Reference", "Optional supplier-side reference number.", "String", false, maxLength: 128),
                Field("shippingCharges", "Shipping Charges", "Optional shipping cost.", "Decimal", false, "0", min: 0),
                Field("otherCharges", "Other Charges", "Optional other charges.", "Decimal", false, "0", min: 0),
                Field("notes", "Notes", "Optional notes.", "String", false, maxLength: 1000),
                Field("items", "Items", "One or more line items, each with a Product, Ordered Quantity, and Unit Purchase Price.", "List", true),
            },
            BusinessRules = new()
            {
                "At least one item is required.",
                "The AI creates the order as Draft only - approval, receiving goods, and any stock/ledger impact still happen through the normal Purchase Orders and Goods Receipts screens.",
            },
            RelatedModules = new() { "supplier", "product", "goodsreceipts" },
        });

        // Mirrors CreateShopSaleDto + CreateShopSaleItemDto.
        modules.Add(new ShopAiModuleMetadata
        {
            ModuleKey = "saledraft",
            DisplayName = "Sale",
            Description = "A Sale records products sold to a Customer. Created by the AI Assistant as a Draft only - it does not reduce stock or create customer ledger transactions until completed through the normal Sales/POS screen.",
            CreateAction = ShopAiActionType.CreateSaleDraft,
            RequiredPermission = EHubPermissions.ShopAiAssistant.CreateSaleDraft,
            ExistingCreatePermission = EHubPermissions.ShopSales.Create,
            SupportsCreation = true,
            CreatesDraftOnly = true,
            Aliases = new() { "sale", "sales", "pos", "فروخت", "sale add" },
            Fields = new()
            {
                Field("customerId", "Customer", "Which customer the sale is for.", "String", true, "Ali Traders", isLookup: true, lookupModule: "customer"),
                Field("saleDate", "Sale Date", "The date of the sale.", "DateTime", true),
                Field("dueDate", "Due Date", "Required for Credit sales - when payment is due.", "DateTime", false),
                Field("saleType", "Sale Type", "Cash or Credit.", "Enum", false, allowedValues: new() { "Cash", "Credit" }),
                Field("paymentMethod", "Payment Method", "How the customer paid.", "Enum", false, allowedValues: new() { "Cash", "Bank", "Card", "Cheque", "Other" }),
                Field("paidAmount", "Paid Amount", "Amount the customer paid immediately.", "Decimal", false, "0", min: 0),
                Field("referenceNumber", "Reference Number", "Optional reference number.", "String", false, maxLength: 128),
                Field("otherCharges", "Other Charges", "Optional other charges.", "Decimal", false, "0", min: 0),
                Field("notes", "Notes", "Optional notes.", "String", false, maxLength: 1000),
                Field("items", "Items", "One or more line items, each with a Product, Quantity, and Unit Sale Price.", "List", true),
            },
            BusinessRules = new()
            {
                "At least one item is required.",
                "The AI creates the sale as Draft only - stock reduction and customer ledger entries only happen when the sale is completed through the normal Sales/POS screen.",
            },
            RelatedModules = new() { "customer", "product", "customerpayments" },
        });

        // Mirrors CreateShopStockAdjustmentDto + CreateShopStockAdjustmentItemDto.
        modules.Add(new ShopAiModuleMetadata
        {
            ModuleKey = "stockadjustmentdraft",
            DisplayName = "Stock Adjustment",
            Description = "A Stock Adjustment corrects a product's stock quantity up or down (e.g. for damage or a count discrepancy). Created by the AI Assistant as a Draft only - it does not change stock until posted through the normal Stock Adjustments screen.",
            CreateAction = ShopAiActionType.CreateStockAdjustmentDraft,
            RequiredPermission = EHubPermissions.ShopAiAssistant.CreateStockAdjustmentDraft,
            ExistingCreatePermission = EHubPermissions.ShopStockAdjustments.Create,
            SupportsCreation = true,
            CreatesDraftOnly = true,
            Aliases = new() { "stock adjustment", "stock adjustments", "اسٹاک ایڈجسٹمنٹ", "stock adjustment add" },
            Fields = new()
            {
                Field("adjustmentDate", "Adjustment Date", "The date of the adjustment.", "DateTime", true),
                Field("reason", "Reason", "The overall reason for the adjustment.", "Enum", true, allowedValues: new() { "Damaged", "Lost", "Expired", "CountCorrection", "Other" }),
                Field("reasonDetails", "Reason Details", "Optional extra detail about the reason.", "String", false, maxLength: 500),
                Field("notes", "Notes", "Optional notes.", "String", false, maxLength: 1000),
                Field("items", "Items", "One or more line items, each with a Product, Adjustment Type (Increase/Decrease), and Adjustment Quantity.", "List", true),
            },
            BusinessRules = new()
            {
                "At least one item is required; adjustment quantity must be greater than zero per item.",
                "The AI creates the adjustment as Draft only - stock is only changed once it is posted through the normal Stock Adjustments screen.",
            },
            RelatedModules = new() { "product", "stocktransactions", "productbatches" },
        });

        // Mirrors CreateShopStockCountDto.
        modules.Add(new ShopAiModuleMetadata
        {
            ModuleKey = "physicalstockcountdraft",
            DisplayName = "Physical Stock Count",
            Description = "A Physical Stock Count is a session for counting actual stock on hand and reconciling it against system quantities, for either all products or a chosen scope. Created by the AI Assistant as a Draft only - counting and posting still happen through the normal Stock Counts screen.",
            CreateAction = ShopAiActionType.CreatePhysicalStockCountDraft,
            RequiredPermission = EHubPermissions.ShopAiAssistant.CreatePhysicalStockCountDraft,
            ExistingCreatePermission = EHubPermissions.ShopStockCounts.Create,
            SupportsCreation = true,
            CreatesDraftOnly = true,
            Aliases = new() { "stock count", "physical stock count", "اسٹاک کاؤنٹ", "stock count add" },
            Fields = new()
            {
                Field("countDate", "Count Date", "The date of the count.", "DateTime", true),
                Field("scope", "Scope", "Whether to count all products or a chosen subset.", "Enum", true, allowedValues: new() { "AllProducts", "Category", "SelectedProducts" }),
                Field("productCategoryId", "Category", "Required when Scope is Category.", "String", false, isLookup: true, lookupModule: "productcategory"),
                Field("selectedProductIds", "Selected Products", "Required when Scope is SelectedProducts.", "List", false, isLookup: true, lookupModule: "product"),
                Field("notes", "Notes", "Optional notes.", "String", false, maxLength: 1000),
            },
            BusinessRules = new()
            {
                "The AI creates the count session as Draft only - actual counting and any resulting stock correction happen through the normal Stock Counts screen.",
            },
            RelatedModules = new() { "product", "productcategory", "stocktransactions" },
        });

        // ---------------- Explanation-only modules (no AI creation this round) ----------------

        modules.Add(ExplainOnly("shopsettings", "Shop Settings", "Shop-wide configuration such as the shop's display name, currency code/symbol, decimal places, and tax settings. Every report and dashboard figure is formatted using these settings.", new() { "settings", "shop settings" }));

        modules.Add(ExplainOnly("sales", "Sales / POS", "The point-of-sale screen where a completed sale is finalized: stock is reduced, the customer ledger is updated, and payment status is tracked. This is the 'real' counterpart to the AI's Sale draft - a draft created by the AI must still be opened here to complete it.", new() { "pos", "point of sale" }, related: new() { "saledraft", "customer", "product" }));

        modules.Add(ExplainOnly("goodsreceipts", "Goods Receipts", "Records goods actually received against a Purchase Order. Completing a Goods Receipt increases stock and creates a supplier ledger transaction.", new() { "goods receipt", "receiving" }, related: new() { "purchaseorderdraft", "supplier", "stocktransactions" }));

        modules.Add(ExplainOnly("supplierpayments", "Supplier Payments", "Records money paid to a supplier and allocates it against outstanding Goods Receipts. Posting a payment reduces the supplier's payable balance.", new() { "supplier payment" }, related: new() { "supplier", "supplierledger", "bankaccount" }));

        modules.Add(ExplainOnly("purchasereturns", "Purchase Returns", "Records goods returned to a supplier from a completed Goods Receipt. Completing a return reduces stock and adjusts the supplier ledger.", new() { "purchase return" }, related: new() { "goodsreceipts", "supplier" }));

        modules.Add(ExplainOnly("supplierledger", "Supplier Ledger", "A running statement of everything owed to (or advanced to) a supplier - opening balance, purchases, payments, and returns - with a running balance.", new() { "supplier ledger", "supplier statement" }, related: new() { "supplier", "goodsreceipts", "supplierpayments", "purchasereturns" }));

        modules.Add(ExplainOnly("customerpayments", "Customer Payments", "Records money received from a customer and allocates it against one or more completed Sales. Posting a payment reduces the sales' pending balance.", new() { "customer payment" }, related: new() { "customer", "customerledger", "bankaccount" }));

        modules.Add(ExplainOnly("salereturns", "Sale Returns", "Records products returned by a customer from a completed Sale. Completing a return increases stock back and adjusts the customer ledger (refund or customer credit).", new() { "sale return" }, related: new() { "sales", "customer" }));

        modules.Add(ExplainOnly("customerledger", "Customer Ledger", "A running statement of everything a customer owes (or has as credit) - opening balance, sales, payments, and returns - with a running balance.", new() { "customer ledger", "customer statement" }, related: new() { "customer", "sales", "customerpayments", "salereturns" }));

        modules.Add(ExplainOnly("expenses", "Expenses", "Records shop expenses such as rent or utilities. A Draft expense can be created by the AI, but only reduces cash/bank balance once posted from this screen.", new() { "expenses list" }, related: new() { "expensedraft", "expensecategory", "cashregisters", "bankaccount" }));

        modules.Add(ExplainOnly("cashregisters", "Cash Registers", "Physical or logical cash drawers the shop uses to take in and pay out cash. Every cash-affecting transaction (sale payment, expense, etc.) posts against a cash register.", new() { "cash register", "till" }, related: new() { "cashtransactions", "cashclosings" }));

        modules.Add(ExplainOnly("cashtransactions", "Cash Transactions", "The full movement history (in and out) for a cash register, including manual adjustments as well as transactions generated automatically by sales, payments, and expenses.", new() { "cash transaction", "cash movement" }, related: new() { "cashregisters" }));

        modules.Add(ExplainOnly("cashclosings", "Daily Cash Closing", "The end-of-day process of counting actual cash in a register and reconciling it against the system-expected balance.", new() { "cash closing", "daily closing", "day end" }, related: new() { "cashregisters", "cashtransactions" }));

        modules.Add(ExplainOnly("banktransactions", "Bank Transactions", "The full movement history (in and out) for a bank account, including manual adjustments as well as transactions generated automatically by payments and expenses.", new() { "bank transaction", "bank movement" }, related: new() { "bankaccount" }));

        modules.Add(ExplainOnly("banktransfers", "Bank Transfers", "Moves money between two of the shop's own bank accounts. Posting a transfer debits one account and credits the other.", new() { "bank transfer", "fund transfer" }, related: new() { "bankaccount" }));

        modules.Add(ExplainOnly("stocktransactions", "Stock Transactions", "The full audit trail of every stock quantity change for every product - goods received, sales, returns, adjustments, and stock counts - each showing quantity in/out and running balance.", new() { "stock transaction", "stock movement", "inventory movement" }, related: new() { "product", "goodsreceipts", "sales", "stockadjustmentdraft" }));

        modules.Add(ExplainOnly("productbatches", "Product Batches / Expiry", "Tracks individual batches of a product (batch number, expiry date, quantity) for products with batch or expiry tracking enabled, used for FEFO allocation and expiry alerts.", new() { "batch", "batches", "expiry", "expiry management" }, related: new() { "product", "stocktransactions" }));

        modules.Add(ExplainOnly("dashboard", "Dashboard", "A read-only summary view of today's/this period's sales, expenses, balances, low-stock and near-expiry alerts, top products, and recent transactions.", new() { "dashboard", "overview" }, related: new() { "sales", "expenses" }));

        modules.Add(ExplainOnly("reports", "Reports", "A collection of read-only reports covering sales, purchases, stock, customer/supplier receivables and payables, expenses, cash, bank, tax summary, and product performance.", new() { "reports", "reporting" }));

        modules.Add(ExplainOnly("aiassistant", "AI Assistant", "This chat assistant itself - it can answer questions about any Shop Management module and guide you through creating a limited set of records, always asking for confirmation before creating anything.", new() { "ai assistant", "assistant", "chatbot" }));

        return modules;
    }

    private static ShopAiModuleMetadata ExplainOnly(string key, string displayName, string description, List<string> aliases, List<string>? related = null) => new()
    {
        ModuleKey = key,
        DisplayName = displayName,
        Description = description,
        SupportsCreation = false,
        RequiresConfirmation = false,
        RequiredPermission = string.Empty,
        ExistingCreatePermission = string.Empty,
        Aliases = aliases,
        RelatedModules = related ?? new List<string>(),
    };
}
