import { mapEnumToOptions } from '@abp/ng.core';

export enum City {
  Unknown = 0,
  Islamabad = 1,
  Lahore = 2,
  Rawalpindi = 3,
  Faisalabad = 4,
  Multan = 5,
  Gujranwala = 6,
  Sialkot = 7,
  Bahawalpur = 8,
  Sargodha = 9,
  Sheikhupura = 10,
  RahimYarKhan = 11,
  Jhang = 12,
  Gujrat = 13,
  Karachi = 14,
  Hyderabad = 15,
  Sukkur = 16,
  Larkana = 17,
  Nawabshah = 18,
  MirpurKhas = 19,
  Thatta = 21,
  Peshawar = 21,
  Mardan = 22,
  Mingora = 23,
  Abbottabad = 24,
  Kohat = 25,
  DeraIsmailKhan = 26,
  Swabi = 27,
  Nowshera = 28,
  Quetta = 29,
  Gwadar = 30,
  Khuzdar = 31,
  Turbat = 32,
  Chaman = 33,
  Gilgit = 34,
  Skardu = 35,
  Hunza = 36,
  Muzaffarabad = 37,
  Mirpur = 38,
  Kotli = 39,
}

export const cityOptions = mapEnumToOptions(City);
