using System; using System.Collections.Generic; using System.Linq; using System.Threading.Tasks; using Microsoft.AspNetCore.Authorization; using Volo.Abp; using Volo.Abp.Application.Dtos; using Volo.Abp.Application.Services; using Volo.Abp.Domain.Repositories; using EHub.Permissions; using EHub.ShopManagement.GoodsReceipts; using EHub.ShopManagement.Products; using EHub.ShopManagement.PurchaseOrders; using EHub.ShopManagement.StockTransactions; using EHub.ShopManagement.Suppliers; using EHub.ShopManagement.Units;
namespace EHub.ShopManagement.PurchaseReturns;
[Authorize(EHubPermissions.ShopPurchaseReturns.Default)] public class ShopPurchaseReturnAppService : ApplicationService, IShopPurchaseReturnAppService
{
 readonly IRepository<ShopPurchaseReturn,Guid> returns; readonly IRepository<ShopPurchaseReturnItem,Guid> returnItems; readonly IRepository<ShopGoodsReceipt,Guid> receipts; readonly IRepository<ShopGoodsReceiptItem,Guid> receiptItems; readonly IRepository<ShopSupplier,Guid> suppliers; readonly IRepository<ShopProduct,Guid> products; readonly IRepository<ShopUnit,Guid> units; readonly IRepository<ShopStockTransaction,Guid> stock; readonly ShopDocumentNumberGenerator numbers;
 public ShopPurchaseReturnAppService(IRepository<ShopPurchaseReturn,Guid>a,IRepository<ShopPurchaseReturnItem,Guid>b,IRepository<ShopGoodsReceipt,Guid>c,IRepository<ShopGoodsReceiptItem,Guid>d,IRepository<ShopSupplier,Guid>e,IRepository<ShopProduct,Guid>f,IRepository<ShopUnit,Guid>g,IRepository<ShopStockTransaction,Guid>h,ShopDocumentNumberGenerator n){returns=a;returnItems=b;receipts=c;receiptItems=d;suppliers=e;products=f;units=g;stock=h;numbers=n;}
 public async Task<PagedResultDto<ShopPurchaseReturnDto>> GetListAsync(GetShopPurchaseReturnsInput i){var t=Tenant();var q=await returns.WithDetailsAsync(x=>x.Items);q=q.Where(x=>x.TenantId==t).WhereIf(!i.Filter.IsNullOrWhiteSpace(),x=>x.PurchaseReturnNumber.Contains(i.Filter!)).WhereIf(i.SupplierId.HasValue,x=>x.SupplierId==i.SupplierId).WhereIf(i.GoodsReceiptId.HasValue,x=>x.GoodsReceiptId==i.GoodsReceiptId).WhereIf(i.Status.HasValue,x=>x.Status==i.Status).WhereIf(i.FromDate.HasValue,x=>x.ReturnDate>=i.FromDate).WhereIf(i.ToDate.HasValue,x=>x.ReturnDate<i.ToDate!.Value.AddDays(1));var count=await AsyncExecuter.CountAsync(q);var rows=await AsyncExecuter.ToListAsync(q.OrderByDescending(x=>x.ReturnDate).Skip(i.SkipCount).Take(i.MaxResultCount));var dtos=new List<ShopPurchaseReturnDto>();foreach(var x in rows)dtos.Add(await Map(x));return new(count,dtos);}
 public async Task<ShopPurchaseReturnDto> GetAsync(Guid id)=>await Map(await Find(id));
 public async Task<ShopGoodsReceiptReturnableDto> GetGoodsReceiptForReturnAsync(Guid id){var t=Tenant();var r=await receipts.GetAsync(x=>x.Id==id&&x.TenantId==t);if(r.Status!=ShopGoodsReceiptStatus.Completed)throw new BusinessException("ShopManagement:PurchaseReturnRequiresCompletedGoodsReceipt");var s=await suppliers.GetAsync(r.SupplierId);var q=await receiptItems.GetQueryableAsync();var source=await AsyncExecuter.ToListAsync(q.Where(x=>x.GoodsReceiptId==id&&x.TenantId==t));var dto=new ShopGoodsReceiptReturnableDto{Id=id,GoodsReceiptNumber=r.GoodsReceiptNumber,SupplierId=s.Id,SupplierName=s.Name,ReceiptDate=r.ReceiptDate};var cost=await AuthorizationService.IsGrantedAsync(EHubPermissions.ShopPurchaseReturns.ViewCost);foreach(var x in source){var prev=await Returned(x.Id,t);var available=x.ReceivedQuantity+x.BonusQuantity-prev;if(available<=0)continue;var p=await products.GetAsync(x.ProductId);var u=await units.GetAsync(p.UnitId);dto.Items.Add(new(){Id=x.Id,ProductId=x.ProductId,ProductName=x.ProductNameSnapshot,ProductCode=x.ProductCodeSnapshot,UnitName=x.UnitNameSnapshot,UnitShortName=x.UnitShortNameSnapshot,UnitAllowDecimal=u.AllowDecimal,ReceivedQuantity=x.ReceivedQuantity,BonusQuantity=x.BonusQuantity,PreviouslyReturnedQuantity=prev,ReturnableQuantity=available,PurchasePrice=cost?x.PurchasePrice:null,TaxPercentage=x.TaxPercentage,BatchNumber=x.BatchNumber,ExpiryDate=x.ExpiryDate});}return dto;}
 [Authorize(EHubPermissions.ShopPurchaseReturns.Create)] public async Task<ShopPurchaseReturnDto> CreateAsync(CreateShopPurchaseReturnDto i){var t=Tenant();var r=await receipts.GetAsync(x=>x.Id==i.GoodsReceiptId&&x.TenantId==t);if(r.Status!=ShopGoodsReceiptStatus.Completed)throw new BusinessException("ShopManagement:PurchaseReturnRequiresCompletedGoodsReceipt");var id=GuidGenerator.Create();var lines=await Build(id,r,i.Items.Select(x=>(x.GoodsReceiptItemId,x.ReturnQuantity,x.Reason,x.Notes)),t);var e=new ShopPurchaseReturn(id,t,await numbers.GetNextNumberAsync(t,"PurchaseReturn","PR-"),r.SupplierId,r.Id,i.ReturnDate,i.Reason,i.ReasonDetails,i.OtherCharges,i.Notes,lines);await returns.InsertAsync(e,true);return await GetAsync(id);}
 [Authorize(EHubPermissions.ShopPurchaseReturns.Edit)] public async Task<ShopPurchaseReturnDto> UpdateAsync(Guid id,UpdateShopPurchaseReturnDto i){var e=await Find(id);var r=await receipts.GetAsync(e.GoodsReceiptId);e.Update(i.ReturnDate,i.Reason,i.ReasonDetails,i.OtherCharges,i.Notes,await Build(id,r,i.Items.Select(x=>(x.GoodsReceiptItemId,x.ReturnQuantity,x.Reason,x.Notes)),Tenant(),id));await returns.UpdateAsync(e,true);return await GetAsync(id);}
 [Authorize(EHubPermissions.ShopPurchaseReturns.Delete)] public async Task DeleteAsync(Guid id){var e=await Find(id);e.EnsureDraft("Deleted");await returns.DeleteAsync(e,true);}
 [Authorize(EHubPermissions.ShopPurchaseReturns.Complete)] public async Task<ShopPurchaseReturnDto> CompleteAsync(Guid id){var t=Tenant();var e=await Find(id);e.EnsureDraft("Completed");foreach(var x in e.Items){var p=await products.GetAsync(y=>y.Id==x.ProductId&&y.TenantId==t);p.DecreaseStock(x.ReturnQuantity);await products.UpdateAsync(p);await stock.InsertAsync(new ShopStockTransaction(GuidGenerator.Create(),t,p.Id,ShopStockTransactionType.PurchaseReturn,ShopStockReferenceType.PurchaseReturn,e.Id,e.PurchaseReturnNumber,x.Id,Clock.Now,0,x.ReturnQuantity,p.CurrentStock,x.UnitPurchasePrice,x.BatchNumber,x.ExpiryDate,e.Notes,CurrentUser.Id,Clock.Now));}e.Complete(CurrentUser.Id??throw new BusinessException("ShopManagement:UserRequired"),Clock.Now);await returns.UpdateAsync(e,true);return await GetAsync(id);}
 [Authorize(EHubPermissions.ShopPurchaseReturns.Cancel)] public async Task<ShopPurchaseReturnDto> CancelAsync(Guid id,CancelShopPurchaseReturnDto i){var e=await Find(id);e.Cancel(CurrentUser.Id??throw new BusinessException("ShopManagement:UserRequired"),Clock.Now,i.CancellationReason);await returns.UpdateAsync(e,true);return await GetAsync(id);}
 async Task<List<ShopPurchaseReturnItem>> Build(Guid rid,ShopGoodsReceipt r,IEnumerable<(Guid id,decimal qty,ShopPurchaseReturnReason reason,string? notes)> inputs,Guid t,Guid? excluded=null){var list=new List<ShopPurchaseReturnItem>();foreach(var i in inputs){var src=await receiptItems.GetAsync(x=>x.Id==i.id&&x.GoodsReceiptId==r.Id&&x.TenantId==t);var p=await products.GetAsync(src.ProductId);var u=await units.GetAsync(p.UnitId);list.Add(new(GuidGenerator.Create(),t,rid,src,await Returned(src.Id,t,excluded),i.qty,u.AllowDecimal,i.reason,i.notes));}return list;}
 async Task<decimal> Returned(Guid item,Guid t,Guid? excluded=null){var iq=await returnItems.GetQueryableAsync();var rq=await returns.GetQueryableAsync();var q=from i in iq join r in rq on i.PurchaseReturnId equals r.Id where i.GoodsReceiptItemId==item&&i.TenantId==t&&r.Status==ShopPurchaseReturnStatus.Completed&&(!excluded.HasValue||r.Id!=excluded) select i.ReturnQuantity;return (await AsyncExecuter.ToListAsync(q)).Sum();}
 async Task<ShopPurchaseReturn> Find(Guid id){var t=Tenant();var q=await returns.WithDetailsAsync(x=>x.Items);return await AsyncExecuter.FirstOrDefaultAsync(q.Where(x=>x.Id==id&&x.TenantId==t))??throw new BusinessException("ShopManagement:PurchaseReturnNotFound");}
 async Task<ShopPurchaseReturnDto> Map(ShopPurchaseReturn e){var s=await suppliers.GetAsync(e.SupplierId);var r=await receipts.GetAsync(e.GoodsReceiptId);var c=await AuthorizationService.IsGrantedAsync(EHubPermissions.ShopPurchaseReturns.ViewCost);return new(){Id=e.Id,PurchaseReturnNumber=e.PurchaseReturnNumber,SupplierId=e.SupplierId,SupplierName=s.Name,GoodsReceiptId=e.GoodsReceiptId,GoodsReceiptNumber=r.GoodsReceiptNumber,ReturnDate=e.ReturnDate,Status=e.Status,Reason=e.Reason,ReasonDetails=e.ReasonDetails,SubTotal=c?e.SubTotal:null,TaxAmount=c?e.TaxAmount:null,OtherCharges=e.OtherCharges,GrandTotal=c?e.GrandTotal:null,Notes=e.Notes,CompletedDate=e.CompletedDate,CancelledDate=e.CancelledDate,CancellationReason=e.CancellationReason,CreationTime=e.CreationTime,Items=e.Items.Select(x=>new ShopPurchaseReturnItemDto{Id=x.Id,GoodsReceiptItemId=x.GoodsReceiptItemId,ProductId=x.ProductId,ProductNameSnapshot=x.ProductNameSnapshot,ProductCodeSnapshot=x.ProductCodeSnapshot,UnitNameSnapshot=x.UnitNameSnapshot,UnitShortNameSnapshot=x.UnitShortNameSnapshot,BatchNumber=x.BatchNumber,ExpiryDate=x.ExpiryDate,ReceivedQuantitySnapshot=x.ReceivedQuantitySnapshot,PreviouslyReturnedQuantity=x.PreviouslyReturnedQuantity,ReturnQuantity=x.ReturnQuantity,UnitPurchasePrice=c?x.UnitPurchasePrice:null,TaxPercentage=x.TaxPercentage,TaxAmount=c?x.TaxAmount:null,LineSubTotal=c?x.LineSubTotal:null,LineTotal=c?x.LineTotal:null,Reason=x.Reason,Notes=x.Notes}).ToList()};}
 Guid Tenant()=>CurrentTenant.Id??throw new BusinessException("ShopManagement:TenantRequired");
}
