import {
  AfterViewInit,
  ChangeDetectorRef,
  Component,
  ElementRef,
  OnDestroy,
  OnInit,
  ViewChild,
} from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { finalize } from 'rxjs/operators';

import { Chart, ChartConfiguration, registerables } from 'chart.js';
import {
  DashboardService,
  TimePointByCategoryDto,
  // ✅ if generated by proxy after backend change:
  // TimePointByNameDto,
} from '../proxy/dashboards';

Chart.register(...registerables);

/** ===== Backend Contracts (match C# exactly) ===== */
export interface DashboardInput {
  month?: string | null; // "yyyy-MM"
  fromDate?: string | null; // "yyyy-MM-dd" or any JS date string
  toDate?: string | null;

  gradeLevel?: number | null;
  section?: number | null;
  shift?: number | null;
  term?: number | null;

  department?: number | null;
}

export interface DashboardDto {
  kpis: DashboardKpisDto;

  expenseTrend: TimePointDto[];
  earnTrend: TimePointDto[];

  expenseTrendByCategory: TimePointByCategoryDto[];

  // ✅ Salary breakdown for expense tooltip (backend must send this)
  salaryTrendByStaff: TimePointByNameDto[];

  staffStatus: AttendanceStatusDistributionDto;
  studentStatus: AttendanceStatusDistributionDto;

  topStaff: AttendanceLeaderboardItemDto[];
  bottomStaff: AttendanceLeaderboardItemDto[];

  studentAttendanceByClass: ClassAttendanceDto[];
  topStudentsOverall: StudentTopDto[];
}

export interface DashboardKpisDto {
  totalExpense: number;
  totalEarned: number;
  netProfit: number;
  totalTransactions: number;
}

export interface TimePointDto {
  date: string; // ISO string from backend
  amount: number;
}

// ✅ If proxy didn’t generate, keep this interface locally
export interface TimePointByNameDto {
  date: string;
  name: string;
  amount: number;
}

export interface AttendanceStatusDistributionDto {
  total: number;
  present: number;
  absent: number;
  late: number;
  excused: number;
  sick: number;
  leave: number;
  holiday: number;
  other: number;
}

export interface AttendanceLeaderboardItemDto {
  id: string;
  code: string;
  name: string;
  totalDays: number;
  presentDays: number;
  absentDays: number;
  lateDays: number;
  attendanceRate: number;
}

export interface ClassAttendanceDto {
  gradeLevel: number;
  section: number;
  totalDays: number;
  presentDays: number;
  attendanceRate: number;
}

export interface StudentTopDto {
  studentId: string;
  admissionNo: string;
  fullName: string;
  gradeLevel: number;
  section: number;
  totalDays: number;
  presentDays: number;
  attendanceRate: number;
}

@Component({
  standalone: false,
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss'],
})
export class DashboardComponent implements OnInit, AfterViewInit, OnDestroy {
  form!: FormGroup;

  data: DashboardDto | null = null;
  loading = false;
  showFilters = false; 

  private viewReady = false;
  private renderQueued = false;

  /** ===== Canvas refs ===== */
  @ViewChild('incomeExpenseTrendCanvas') incomeExpenseTrendCanvas?: ElementRef<HTMLCanvasElement>;
  @ViewChild('studentStatusCanvas') studentStatusCanvas?: ElementRef<HTMLCanvasElement>;
  @ViewChild('staffStatusCanvas') staffStatusCanvas?: ElementRef<HTMLCanvasElement>;
  @ViewChild('classAttendanceBarCanvas') classAttendanceBarCanvas?: ElementRef<HTMLCanvasElement>;
  @ViewChild('topStudentsBarCanvas') topStudentsBarCanvas?: ElementRef<HTMLCanvasElement>;

  /** ===== Chart instances ===== */
  private incomeExpenseTrendChart?: Chart;
  private studentStatusChart?: Chart;
  private staffStatusChart?: Chart;
  private classAttendanceChart?: Chart;
  private topStudentsChart?: Chart;

  constructor(
    private fb: FormBuilder,
    private dashboardService: DashboardService,
    private cdRef: ChangeDetectorRef,
  ) {}

  ngOnInit(): void {
    const now = new Date();
    const defaultMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;

    this.form = this.fb.group({
      month: [defaultMonth],
      fromDate: [null],
      toDate: [null],
      gradeLevel: [null],
      section: [null],
      department: [null],
    });

    this.refresh();
  }

   toggleFilters(): void {
    this.showFilters = !this.showFilters;
  }

  ngAfterViewInit(): void {
    this.viewReady = true;
    this.tryRenderCharts();
  }

  ngOnDestroy(): void {
    this.destroyCharts();
  }

  refresh(): void {
    const input: DashboardInput = this.buildInput();

    this.loading = true;
    this.dashboardService
      .get(input)
      .pipe(finalize(() => (this.loading = false)))
      .subscribe({
        next: (res: any) => {
          // ✅ Normalize missing arrays to avoid crashes
          this.data = {
            ...res,
            expenseTrend: res?.expenseTrend ?? [],
            earnTrend: res?.earnTrend ?? [],
            expenseTrendByCategory: res?.expenseTrendByCategory ?? [],
            salaryTrendByStaff: res?.salaryTrendByStaff ?? [],
          } as DashboardDto;

          this.cdRef.detectChanges();
          this.tryRenderCharts();
        },
        error: err => {
          console.error('Dashboard API error:', err);
          this.data = null;
          this.destroyCharts();
        },
      });
  }

  apply(): void {
    this.refresh();
  }

  reset(): void {
    const now = new Date();
    const defaultMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;

    this.form.patchValue({
      month: defaultMonth,
      fromDate: null,
      toDate: null,
      gradeLevel: null,
      section: null,
      department: null,
    });

    this.refresh();
  }

  /** ===== Helpers ===== */

  private buildInput(): DashboardInput {
    const v = this.form.value;

    const month = this.toNullableString(v.month);
    const fromDate = this.toNullableString(v.fromDate);
    const toDate = this.toNullableString(v.toDate);

    return {
      month,
      fromDate,
      toDate,
      gradeLevel: this.toNullableNumber(v.gradeLevel),
      section: this.toNullableNumber(v.section),
      department: this.toNullableNumber(v.department),
    };
  }

  private toNullableString(x: any): string | null {
    const s = (x ?? '').toString().trim();
    return s.length ? s : null;
  }

  private toNullableNumber(x: any): number | null {
    if (x === null || x === undefined || x === '') return null;
    const n = Number(x);
    return Number.isFinite(n) ? n : null;
  }

  private tryRenderCharts(): void {
    if (!this.viewReady) return;
    if (!this.data) return;

    if (this.renderQueued) return;
    this.renderQueued = true;

    setTimeout(() => {
      this.renderQueued = false;
      this.initOrUpdateCharts();
    }, 0);
  }

  private destroyCharts(): void {
    this.incomeExpenseTrendChart?.destroy();
    this.studentStatusChart?.destroy();
    this.staffStatusChart?.destroy();
    this.classAttendanceChart?.destroy();
    this.topStudentsChart?.destroy();

    this.incomeExpenseTrendChart = undefined;
    this.studentStatusChart = undefined;
    this.staffStatusChart = undefined;
    this.classAttendanceChart = undefined;
    this.topStudentsChart = undefined;
  }

  private initOrUpdateCharts(): void {
    if (!this.data) return;

    this.destroyCharts();

    this.buildIncomeVsExpenseTrend();
    this.buildStudentStatusChart();
    this.buildStaffStatusChart();
    this.buildClassAttendanceBar();
    this.buildTopStudentsBar();
  }

  private getCanvas2d(ref?: ElementRef<HTMLCanvasElement>): CanvasRenderingContext2D | null {
    if (!ref?.nativeElement) return null;
    return ref.nativeElement.getContext('2d');
  }

  private dateKey(x: string | undefined | null): string {
    return String(x ?? '').slice(0, 10);
  }

  private fmt(n: any): string {
    const v = Number(n ?? 0);
    return Number.isFinite(v) ? v.toLocaleString() : '0';
  }

  /** ===== Chart Builders ===== */

  private buildIncomeVsExpenseTrend(): void {
    const ctx = this.getCanvas2d(this.incomeExpenseTrendCanvas);
    if (!ctx || !this.data) return;

    const expense = this.data.expenseTrend ?? [];
    const earn = this.data.earnTrend ?? [];

    // unify labels by day across both series
    const allDates = Array.from(
      new Set([...expense.map(x => this.dateKey(x.date)), ...earn.map(x => this.dateKey(x.date))]),
    ).sort();

    const expenseMap = new Map(expense.map(x => [this.dateKey(x.date), x.amount]));
    const earnMap = new Map(earn.map(x => [this.dateKey(x.date), x.amount]));

    const labels = allDates;
    const expenseData = labels.map(d => expenseMap.get(d) ?? 0);
    const earnData = labels.map(d => earnMap.get(d) ?? 0);

    const config: ChartConfiguration<'line'> = {
      type: 'line',
      data: {
        labels,
        datasets: [
          // ✅ Expense = RED
          {
            label: 'Expense',
            data: expenseData,
            tension: 0.35,
            fill: false,
            pointRadius: 3,
            borderColor: '#ff4d6d',
            backgroundColor: '#ff4d6d',
            pointBorderColor: '#ff4d6d',
            pointBackgroundColor: '#ff4d6d',
          },

          // ✅ Earn = BLUE
          {
            label: 'Earn',
            data: earnData,
            tension: 0.35,
            fill: false,
            pointRadius: 3,
            borderColor: '#2f80ed',
            backgroundColor: '#2f80ed',
            pointBorderColor: '#2f80ed',
            pointBackgroundColor: '#2f80ed',
          },
        ],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: { display: true },

          tooltip: {
            callbacks: {
              title: items => items?.[0]?.label ?? '',

              // ✅ Main label line
              label: tooltipCtx => {
                const value = Number(tooltipCtx.parsed?.y ?? 0);
                const d = this.dateKey(String(tooltipCtx.label ?? ''));
                const datasetLabel = String(tooltipCtx.dataset?.label ?? '').toLowerCase();

                if (datasetLabel === 'expense') {
                  // show total only here; details go in afterBody
                  return `Expense Total: ${this.fmt(value)}`;
                }

                if (datasetLabel === 'earn') {
                  return `Earn: ${this.fmt(value)}`;
                }

                return this.fmt(value);
              },

              // ✅ Details breakdown
              afterBody: items => {
                const item = items?.[0];
                if (!item || !this.data) return [];

                const datasetLabel = String(item.dataset?.label ?? '').toLowerCase();
                const d = this.dateKey(String(item.label ?? ''));

                // Only expense tooltip breakdown
                if (datasetLabel !== 'expense') return [];

                const lines: string[] = [];

                // 1) Expense categories (ExpenseEntry)
                const cats = (this.data.expenseTrendByCategory ?? [])
                  .filter(x => this.dateKey(x.date as any) === d)
                  .sort((a, b) => Number(b.amount ?? 0) - Number(a.amount ?? 0));

                if (cats.length) {
                  lines.push('Expense Categories');
                  for (const r of cats) {
                    lines.push(`- ${r.categoryName}: ${this.fmt(r.amount)}`);
                  }
                }

                // 2) Salary by staff (StaffSalaryPayment)
                const staffRows = (this.data.salaryTrendByStaff ?? [])
                  .filter(x => this.dateKey(x.date) === d)
                  .sort((a, b) => Number(b.amount ?? 0) - Number(a.amount ?? 0));

                if (staffRows.length) {
                  if (lines.length) lines.push(''); // spacing line
                  lines.push('Staff Salaries');
                  for (const r of staffRows) {
                    lines.push(`- ${r.name}: ${this.fmt(r.amount)}`);
                  }
                }

                return lines;
              },
            },
          },
        },

        scales: {
          x: { ticks: { maxRotation: 0 } },
          y: { beginAtZero: true },
        },
      },
    };

    this.incomeExpenseTrendChart = new Chart(ctx, config);
  }

  private buildStudentStatusChart(): void {
    const ctx = this.getCanvas2d(this.studentStatusCanvas);
    if (!ctx || !this.data) return;

    const s = this.data.studentStatus;
    const labels = ['Present', 'Absent', 'Late', 'Excused', 'Sick', 'Leave', 'Holiday', 'Other'];
    const values = [s.present, s.absent, s.late, s.excused, s.sick, s.leave, s.holiday, s.other];

    const config: ChartConfiguration<'doughnut'> = {
      type: 'doughnut',
      data: {
        labels,
        datasets: [{ data: values }],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { position: 'top' } },
        cutout: '65%',
      },
    };

    this.studentStatusChart = new Chart(ctx, config);
  }

  private buildStaffStatusChart(): void {
    const ctx = this.getCanvas2d(this.staffStatusCanvas);
    if (!ctx || !this.data) return;

    const s = this.data.staffStatus;
    const labels = ['Present', 'Absent', 'Late', 'Excused', 'Sick', 'Leave', 'Holiday', 'Other'];
    const values = [s.present, s.absent, s.late, s.excused, s.sick, s.leave, s.holiday, s.other];

    const config: ChartConfiguration<'doughnut'> = {
      type: 'doughnut',
      data: {
        labels,
        datasets: [{ data: values }],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { position: 'top' } },
        cutout: '65%',
      },
    };

    this.staffStatusChart = new Chart(ctx, config);
  }

  private buildClassAttendanceBar(): void {
    const ctx = this.getCanvas2d(this.classAttendanceBarCanvas);
    if (!ctx || !this.data) return;

    const rows = this.data.studentAttendanceByClass ?? [];
    const labels = rows.map(x => `G${x.gradeLevel}-S${x.section}`);
    const values = rows.map(x => x.attendanceRate ?? 0);

    const config: ChartConfiguration<'bar'> = {
      type: 'bar',
      data: {
        labels,
        datasets: [{ label: 'Attendance Rate (%)', data: values }],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { display: true } },
        scales: {
          y: { beginAtZero: true, max: 100 },
        },
      },
    };

    this.classAttendanceChart = new Chart(ctx, config);
  }

  private buildTopStudentsBar(): void {
    const ctx = this.getCanvas2d(this.topStudentsBarCanvas);
    if (!ctx || !this.data) return;

    const rows = this.data.topStudentsOverall ?? [];
    const labels = rows.map(x => x.fullName);
    const values = rows.map(x => x.attendanceRate ?? 0);

    const config: ChartConfiguration<'bar'> = {
      type: 'bar',
      data: {
        labels,
        datasets: [{ label: 'Attendance Rate (%)', data: values }],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { display: true } },
        scales: {
          y: { beginAtZero: true, max: 100 },
        },
      },
    };

    this.topStudentsChart = new Chart(ctx, config);
  }
}
