using System; using Volo.Abp; using Volo.Abp.Domain.Entities.Auditing; using Volo.Abp.MultiTenancy; using EHub.ShopManagement.GoodsReceipts; using EHub.ShopManagement.Products;
namespace EHub.ShopManagement.PurchaseReturns;
public class ShopPurchaseReturnItem : AuditedEntity<Guid>, IMultiTenant
{
    public Guid? TenantId { get; protected set; } public Guid PurchaseReturnId { get; protected set; } public ShopPurchaseReturn? PurchaseReturn { get; protected set; }
    public Guid GoodsReceiptItemId { get; protected set; } public ShopGoodsReceiptItem? GoodsReceiptItem { get; protected set; } public Guid ProductId { get; protected set; } public ShopProduct? Product { get; protected set; }
    public string ProductNameSnapshot { get; protected set; }=string.Empty; public string ProductCodeSnapshot { get; protected set; }=string.Empty; public string UnitNameSnapshot { get; protected set; }=string.Empty; public string UnitShortNameSnapshot { get; protected set; }=string.Empty;
    public string? BatchNumber { get; protected set; } public DateTime? ExpiryDate { get; protected set; } public decimal ReceivedQuantitySnapshot { get; protected set; } public decimal PreviouslyReturnedQuantity { get; protected set; } public decimal ReturnQuantity { get; protected set; }
    public decimal UnitPurchasePrice { get; protected set; } public decimal TaxPercentage { get; protected set; } public decimal TaxAmount { get; protected set; } public decimal LineSubTotal { get; protected set; } public decimal LineTotal { get; protected set; }
    public ShopPurchaseReturnReason Reason { get; protected set; } public string? Notes { get; protected set; }
    protected ShopPurchaseReturnItem() { }
    public ShopPurchaseReturnItem(Guid id,Guid tenantId,Guid returnId,ShopGoodsReceiptItem source,decimal previouslyReturned,decimal quantity,bool allowDecimal,ShopPurchaseReturnReason reason,string? notes):base(id)
    { if(quantity<=0) throw new BusinessException("ShopManagement:PurchaseReturnQuantityMustBePositive"); var available=source.ReceivedQuantity+source.BonusQuantity-previouslyReturned; if(quantity>available) throw new BusinessException("ShopManagement:PurchaseReturnQuantityExceedsReturnable"); if(!allowDecimal && quantity!=decimal.Truncate(quantity)) throw new BusinessException("ShopManagement:PurchaseReturnWholeQuantityRequired"); TenantId=tenantId;PurchaseReturnId=returnId;GoodsReceiptItemId=source.Id;ProductId=source.ProductId;ProductNameSnapshot=source.ProductNameSnapshot;ProductCodeSnapshot=source.ProductCodeSnapshot;UnitNameSnapshot=source.UnitNameSnapshot;UnitShortNameSnapshot=source.UnitShortNameSnapshot;BatchNumber=source.BatchNumber;ExpiryDate=source.ExpiryDate;ReceivedQuantitySnapshot=source.ReceivedQuantity+source.BonusQuantity;PreviouslyReturnedQuantity=previouslyReturned;ReturnQuantity=quantity;UnitPurchasePrice=source.PurchasePrice;TaxPercentage=source.TaxPercentage;Reason=reason;Notes=Check.Length(notes?.Trim(),nameof(notes),ShopPurchaseReturnConsts.NotesMaxLength);LineSubTotal=Round(quantity*UnitPurchasePrice);TaxAmount=Round(LineSubTotal*TaxPercentage/100);LineTotal=Round(LineSubTotal+TaxAmount); }
    private static decimal Round(decimal value)=>Math.Round(value,2,MidpointRounding.AwayFromZero);
}
