using System; using System.Collections.Generic; using System.ComponentModel.DataAnnotations; using System.Threading.Tasks; using Volo.Abp.Application.Dtos; using Volo.Abp.Application.Services;
namespace EHub.ShopManagement.PurchaseReturns;
public class ShopPurchaseReturnItemDto : EntityDto<Guid> { public Guid GoodsReceiptItemId{get;set;} public Guid ProductId{get;set;} public string ProductNameSnapshot{get;set;}=""; public string ProductCodeSnapshot{get;set;}=""; public string UnitNameSnapshot{get;set;}=""; public string UnitShortNameSnapshot{get;set;}=""; public string? BatchNumber{get;set;} public DateTime? ExpiryDate{get;set;} public decimal ReceivedQuantitySnapshot{get;set;} public decimal PreviouslyReturnedQuantity{get;set;} public decimal ReturnQuantity{get;set;} public decimal? UnitPurchasePrice{get;set;} public decimal TaxPercentage{get;set;} public decimal? TaxAmount{get;set;} public decimal? LineSubTotal{get;set;} public decimal? LineTotal{get;set;} public ShopPurchaseReturnReason Reason{get;set;} public string? Notes{get;set;} }
public class ShopPurchaseReturnDto : FullAuditedEntityDto<Guid> { public string PurchaseReturnNumber{get;set;}=""; public Guid SupplierId{get;set;} public string SupplierName{get;set;}=""; public Guid GoodsReceiptId{get;set;} public string GoodsReceiptNumber{get;set;}=""; public DateTime ReturnDate{get;set;} public ShopPurchaseReturnStatus Status{get;set;} public ShopPurchaseReturnReason Reason{get;set;} public string? ReasonDetails{get;set;} public decimal? SubTotal{get;set;} public decimal? TaxAmount{get;set;} public decimal OtherCharges{get;set;} public decimal? GrandTotal{get;set;} public string? Notes{get;set;} public DateTime? CompletedDate{get;set;} public DateTime? CancelledDate{get;set;} public string? CancellationReason{get;set;} public List<ShopPurchaseReturnItemDto> Items{get;set;}=new(); }
public class CreateShopPurchaseReturnItemDto { [Required] public Guid GoodsReceiptItemId{get;set;} [Range(typeof(decimal),"0.0001","999999999999")] public decimal ReturnQuantity{get;set;} public ShopPurchaseReturnReason Reason{get;set;} public string? Notes{get;set;} }
public class UpdateShopPurchaseReturnItemDto : CreateShopPurchaseReturnItemDto { }
public class CreateShopPurchaseReturnDto { [Required] public Guid GoodsReceiptId{get;set;} public DateTime ReturnDate{get;set;} public ShopPurchaseReturnReason Reason{get;set;} public string? ReasonDetails{get;set;} [Range(0,double.MaxValue)] public decimal OtherCharges{get;set;} public string? Notes{get;set;} [MinLength(1)] public List<CreateShopPurchaseReturnItemDto> Items{get;set;}=new(); }
public class UpdateShopPurchaseReturnDto { public DateTime ReturnDate{get;set;} public ShopPurchaseReturnReason Reason{get;set;} public string? ReasonDetails{get;set;} [Range(0,double.MaxValue)] public decimal OtherCharges{get;set;} public string? Notes{get;set;} [MinLength(1)] public List<UpdateShopPurchaseReturnItemDto> Items{get;set;}=new(); }
public class GetShopPurchaseReturnsInput : PagedAndSortedResultRequestDto { public string? Filter{get;set;} public Guid? SupplierId{get;set;} public Guid? GoodsReceiptId{get;set;} public ShopPurchaseReturnStatus? Status{get;set;} public DateTime? FromDate{get;set;} public DateTime? ToDate{get;set;} }
public class ShopGoodsReceiptReturnableItemDto : EntityDto<Guid> { public Guid ProductId{get;set;} public string ProductName{get;set;}=""; public string ProductCode{get;set;}=""; public string UnitName{get;set;}=""; public string UnitShortName{get;set;}=""; public bool UnitAllowDecimal{get;set;} public decimal ReceivedQuantity{get;set;} public decimal BonusQuantity{get;set;} public decimal PreviouslyReturnedQuantity{get;set;} public decimal ReturnableQuantity{get;set;} public decimal? PurchasePrice{get;set;} public decimal TaxPercentage{get;set;} public string? BatchNumber{get;set;} public DateTime? ExpiryDate{get;set;} }
public class ShopGoodsReceiptReturnableDto : EntityDto<Guid> { public string GoodsReceiptNumber{get;set;}=""; public Guid SupplierId{get;set;} public string SupplierName{get;set;}=""; public DateTime ReceiptDate{get;set;} public List<ShopGoodsReceiptReturnableItemDto> Items{get;set;}=new(); }
public class CancelShopPurchaseReturnDto { [Required] public string CancellationReason{get;set;}=""; }
public interface IShopPurchaseReturnAppService : IApplicationService { Task<PagedResultDto<ShopPurchaseReturnDto>> GetListAsync(GetShopPurchaseReturnsInput input); Task<ShopPurchaseReturnDto> GetAsync(Guid id); Task<ShopGoodsReceiptReturnableDto> GetGoodsReceiptForReturnAsync(Guid goodsReceiptId); Task<ShopPurchaseReturnDto> CreateAsync(CreateShopPurchaseReturnDto input); Task<ShopPurchaseReturnDto> UpdateAsync(Guid id,UpdateShopPurchaseReturnDto input); Task DeleteAsync(Guid id); Task<ShopPurchaseReturnDto> CompleteAsync(Guid id); Task<ShopPurchaseReturnDto> CancelAsync(Guid id,CancelShopPurchaseReturnDto input); }
